services:
  jupyter:
    image: jupyter/scipy-notebook:latest
    container_name: jupyter_notebook
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/home/jovyan/work
      - ./data:/data
    environment:
      - DOCKER_STACKS_JUPYTER_CMD=notebook
      - JUPYTER_TOKEN=mysecrettoken
