version: '3.8'

services:
  n8n:
    image: n8nio/n8n
    container_name: 'n8n_cont'
    ports:
      - "5678:5678"
    restart: unless-stopped
    environment:
      - N8N_HOST=${N8N_HOST:-localhost}
      - N8N_PORT=${N8N_PORT:-5678}
      - N8N_PROTOCOL=${N8N_PROTOCOL:-http}
      - N8N_BASIC_AUTH_ACTIVE=${N8N_BASIC_AUTH_ACTIVE:-false}
      - N8N_BASIC_AUTH_USER=yagnik
      - N8N_BASIC_AUTH_PASSWORD=Test@n8n
      - N8N_RUNNERS_ENABLED=true
      - NODE_FUNCTION_ALLOW_EXTERNAL=${NODE_FUNCTION_ALLOW_EXTERNAL:-*} # Crucial for custom NPM modules
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
    volumes:
      - ./n8n_data:/home/node/.n8n
    networks:
      n8n_net:
        ipv4_address: 172.23.1.2

networks:
  n8n_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.23.1.0/28
