version: '3'
services:
  jenkins:
    image: jenkins/jenkins
    container_name: jenkins
    working_dir: /var/jenkins_home
    restart: always
    ports:
      - "3000:8080"
    volumes:
      - "./jenkins_home:/var/jenkins_home"
    networks:
      jenkins-net:
        ipv4_address: 172.3.1.2
networks:
  jenkins-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.3.1.0/29
