# Step 1: Use Node.js image for development
FROM node:18-alpine

# Set working directory inside the container
WORKDIR /app

# Install dependencies
COPY package.json ./

RUN npm install --legacy-peer-deps

# Copy the rest of the application code
COPY . .

# Expose port for React app
EXPOSE 3000

# Start the React app with hot-reloading for development
CMD ["npm", "start"]
