version: "3"
services:
  Documind-frontend-app:
    build:
      context: .
      dockerfile: Dockerfile.react
    image: ${IMAGE_NAME_FRONTEND}
    container_name: "Documind_frontend_dev"
    restart: always
    env_file: .env
    ports:
      - "${Documind_frontend_port}:3000"
    volumes:
      - ./react:/app
      - "Documind_frontend_node_modules:/app/node_modules"
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      Documind-frontend-network:
        ipv4_address: ${Documind_frontend_ip}


  Documind-api-app:
    build:
      context: .
      dockerfile: Dockerfile.node
    image: ${IMAGE_NAME_API}
    container_name: Documind_node_dev
    restart: always
    env_file: .env
    command: ["nodemon","app.js"]
    volumes:
      - ./node:/app
      - "Documind_api_node_modules:/app/node_modules"
    ports:
      - "${Documind_node_port}:3000"
    environment:
      - NODE_ENV=development
    networks:
      Documind-api-network:
        ipv4_address: ${Documind_api_ip}

  Documind_db:
    image: postgres:15
    container_name: Documind_pgdb
    restart: always
    env_file: .env
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PS}
      POSTGRES_DB: ${PG_DB}
    ports:
      - "${Documind_db_port}:5432"
    volumes:
      - ./db-data:/var/lib/postgresql/data
    networks:
      Documind-network:
        ipv4_address: ${Documind_db_ip}

networks:
  Documind-network:
    driver: bridge
    ipam:
      config:
        - subnet: ${Documind_subnet}

volumes:
  Documind_frontend_node_modules:
  Documind_api_node_modules:
